// a workflow that run after a pull request pass the test, add a thank you comment if the pull request pass the test

name: Comment

on:
  workflow_run:
    workflows: ["Scan"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: { pull_request: { number } } } = context
            github.issues.createComment({
              issue_number: number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Thank you for your contribution!"
            })
        if: ${{ github.event.workflow_run.conclusion == 'success' }}