name: PR Thank


on:
  workflow_run:
    workflows: ["Scan", "Build"]
    types:
      - completed

permissions:
  issues: write
  pull-requests: write

jobs:
  comment:
    if: github.event.workflow_run.pull_request.base.ref == github.event.workflow_run.repository.default_branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.event.workflow_run.payload.pull_request.number,
              body: "Thanks very much for contributing! :zap:"
            })
