name: Scan

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Scan
        run: |
          grep -Ri ./ -e "preinstall\|install\|postinstall\|prepublish\|preprepare\|prepare\|postprepare"
          status=$?
          [ $status -eq 0 ] && { echo "No script, please!"; exit 1; }
      - name: Save PR number
        run: |
          mkdir pr
          echo ${{ github.event.number }} > ./pr/pr_number
          echo ${{github.event.pull_request.head.ref}} > ./pr/pr_ref
          echo ${{ github.event.pull_request.head.repo.full_name }} > ./pr/pr_repo
      - uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/
